[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; 串口监视器波特率
monitor_speed = 115200

; 依赖库
lib_deps =
    ; Bodmer 的 TFT_eSPI 是最快最成熟的 ST7789 SPI 驱动
    bodmer/TFT_eSPI @ ^2.5.43

; 将 TFT_eSPI 的用户配置文件指定为本地 include 目录
build_flags =
    -I include
    -D USER_SETUP_LOADED=1
    -D ST7789_DRIVER=1
    -D TFT_WIDTH=240
    -D TFT_HEIGHT=320
    -D TFT_MOSI=23
    -D TFT_SCLK=18
    -D TFT_CS=5
    -D TFT_DC=19
    -D TFT_RST=4
    -D TFT_BL=15
    -D TFT_BACKLIGHT_ON=HIGH
    -D TFT_RGB_ORDER=TFT_BGR
    -D SPI_FREQUENCY=40000000
    -D LOAD_GLCD=1
    -D LOAD_FONT2=1
    -D TOUCH_CS=-1
    -D SUPPRESS_LEGACY_ADC_WARNING
     -D LOAD_FONT4=1
